### ISSUE TITLE
Meta-Boxes: Add meta-boxes

### ISSUE THREAD

**Issue by pretzlaw** [rmp-up/wp-di#2]
Yaml:

```yaml
Foo:
  meta_box:
    foo:
      title: Bar # default "foo"
      screen: 'some_post_type'
      context: side
      priority: low
```

* callback_args later on
