### ISSUE TITLE
Post colums

### ISSUE THREAD

**Issue by pretzlaw** [rmp-up/wp-di#22]
Definition:

```
GenericMetaColumn:
  arguments:
  - 'meta_key'
  manage_posts_custom_column:
    post_type: key
```

Shortcut:

```
PostColumns:
  some-post-type:
    key: service-name
```

Contract:

```
interface PostColumn {
  __toString(): string // label
  __invoke( string $columnName, $id ) {
    // echo content
  }
}
```

* This is not about sortable cols.
