### ISSUE TITLE
Full service definition

### ISSUE THREAD

**Issue by pretzlaw** [rmp-up/wp-di#23]
Proper service definition:

```yaml
service_name:
  class: SomeClass
  # arguments: [] that go into the callable, if not defined then container is passed
  # factory: [] some callable
  other_tags: []
```

- [x] Service definition / parameters
- [x] Custom service using lambda function
- [x] Factory (can be a Closure or public function, possibly another issue)
