### ISSUE TITLE
Missing parameters will fall-back to WP options

### ISSUE THREAD

**Issue by pretzlaw** [rmp-up/wp-di#36]
By now we need to write for every option we use:

```yaml
options:
  blog_public: ~
  ping_sites: ~
  my_own_new_one: 'Hello, hello, hello, how low'

services:
  SomeThing:
    arguments:
      - '%blog_public%'
      - '%ping_sites%'
      - '%my_own_new_one%'
```

If parameters are fetched from options by default, then it could be shorten to this:

```yaml
options:
  my_own_new_one: 'Hello, hello, hello, how low'

services:
  SomeThing:
    arguments:
      - '%blog_public%'
      - '%ping_sites%'
      - '%my_own_new_one%'
```
