### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by pretzlaw** [rmp-up/wp-di#53]
```yaml
translations:
  - 'some-dir/with-translations/'
  - 'en_US.single-translation.yaml'

services:
  Foo:
    arguments: '%bar%'
```

Translation:

```yaml
# en_GB.yaml

This is a complete sentence: Ok cool

wp-di:
  is:
    great: n1
    huge:
      0: Nothing found.
      1: One found
      ">5": %d found

```

Possibly related functions to investigate:

- [ ] get_locale
- [ ] get_user_locale
- [ ] translate
- [ ] translate_with_gettext_context
- [ ] __
- [ ] esc_attr__
- [ ] esc_html__
- [ ] _e
- [ ] esc_attr_e
- [ ] esc_html_e
- [ ] _x
- [ ] _ex
- [ ] esc_attr_x
- [ ] esc_html_x
- [ ] _n
- [ ] _nx
- [ ] _n_noop
- [ ] _nx_noop
- [ ] translate_nooped_plural
- [ ] unload_textdomain
- [ ] _get_path_to_translation
- [ ] _get_path_to_translation_from_lang_dir
- [ ] get_translations_for_domain
- [ ] translate_user_role
- [ ] get_available_languages
- [ ] wp_get_installed_translations
- [ ] switch_to_locale
- [ ] restore_previous_locale
- [ ] restore_current_locale
- [ ] is_locale_switched

**Comment by pretzlaw** [comment]
Now it is possible to:

```yaml
services:
  Foo:
    arguments:
      - !__ [ Bar, baz-domain ]
```

The argument/translation itself will be lazy until needed (service used) or necessary (unused service but a translation needed to be resolved, e.g. for registering things in WordPress).
