### ISSUE TITLE
Shortcodes

### ISSUE THREAD

**Issue by pretzlaw** [rmp-up/wp-di#9]
Short:

```yaml
services:
  Foo:
    shortcode: bar
```

Medium:

```
services:
  Foo:
    shortcode:
      bar: __invoke
```
